name: lineosaurus
description: let's count
author: Nicholas Valentinus
branding:
  icon: align-justify
  color: gray-dark

inputs:
  git-name:
    description: Git name
  git-email:
    description: Git email
  show-credit:
    description: show the credit
    required: false
    default: true
  only_type:
    description: "['.py', '.js']"
    required: false
  ignore_type:
    description: "['.py', '.js']"
    required: false

runs:
  using: 'composite'
  steps:      
    - shell: bash
      env:
        SHOW_CREDIT: ${{ inputs.show-credit }}
      run: |
        git clone https://github.com/nvfp/tweet-posts.git
        cd tweet-posts
        echo "::group::ls $(pwd)"
        ls
        echo "::endgroup::"
        echo "::group::git branch"
        git branch
        echo "::endgroup::"
        echo "::group::git rev-list --count HEAD"
        git rev-list --count HEAD
        echo "::endgroup::"
        python $GITHUB_ACTION_PATH/src/main.py
    - uses: scapeville/action-git-add-all-then-commit-then-push@v1
      with:
        name: ${{ env.git-name }}
        email: ${{ env.git-email }}
        msg: "Updated on $(date +'%Y %b %e, %l:%M %p')"